matrix:
  include:
    - language: python
      python:
        - "3.7-dev"
      install: 
        - pip install -r requirements.txt
      script:
        - pytest

branches:
  only:
  - master

notifications:
  email:
  - joyyeh.tw@gmail.com
