#!/bin/bash

echo 'Reminder: Make sure to run with ". ./activate" to effectively set environment variables!'

source ./.venv/bin/activate

# Add elfin library path
elfinpy_path="$PWD/elfinpy/"
PYTHONPATH=$elfinpy_path:$PYTHONPATH

# Add scripts folder
script_dirs="$PWD/misc/"
PATH=$pelfin_path:$script_dirs:$PATH