#!/bin/bash

echo 'Note: Make sure to run with ". ./activate" to effectively set environment variables!'

source ./venv/bin/activate

# Add elfin library path
PYTHONPATH="$PWD/scripts/Python/:$PYTHONPATH"

export PYTHONPATH