#!/bin/bash

echo 'Reminder: Make sure to run with ". ./activate" to effectively set environment variables!'

source ./.venv/bin/activate

# Add elfin library path
PYTHONPATH="$PWD/scripts/Python/:$PYTHONPATH"

export PYTHONPATH

# Add all scripts folders to path
PATH=$(find ./scripts/ -type d -printf ":%p" ):/$PATH
