#!/bin/bash

cd resources

# Get metadata
rm -rf metadata
echo "Downloading metadata using svn..."
svn export https://github.com/Parmeggiani-Lab/elfin-library-darpin/trunk/metadata

# Get xdb
bz2_file="xdb.json.tar.bz2"
curl 'https://raw.githubusercontent.com/Parmeggiani-Lab/elfin-library-darpin/master/'$bz2_file > "$bz2_file"
tar xjf "$bz2_file"
rm -f "$bz2_file"


# Get aligned and relaxed pdbs
echo
echo
echo '------------------------------------------------------------'
echo 'Attempting acccess to private repo.'
echo "Enter your Github username:"
read github_user
echo "Enter your Github password:"
read -s github_pwd



bz2_file="pdb_aligned.tar.bz2"
curl -u $github_user:$github_pwd 'https://raw.githubusercontent.com/Parmeggiani-Lab/elfin-data/master/'$bz2_file -o $bz2_file; ((ret = ret || $?))
tar xjf "$bz2_file"; ((ret = ret || $?))
rm -f "$bz2_file"; ((ret = ret || $?))

bz2_file="pdb_raw.tar.bz2"
curl -u $github_user:$github_pwd 'https://raw.githubusercontent.com/Parmeggiani-Lab/elfin-data/master/'$bz2_file -o $bz2_file; ((ret = ret || $?))
tar xjf "$bz2_file"; ((ret = ret || $?))
rm -f "$bz2_file"; ((ret = ret || $?))

echo "Done."
