#!/bin/bash

function require_cmd {
	cmd=$1
	command -v "$cmd" >/dev/null 2>&1 || { echo >&2 "$cmd"" is required but not installed. Aborting."; exit 1; }
	echo "$1 is installed."
}

# Check all required commands
require_cmd git

require_cmd svn
require_cmd curl
require_cmd tar

require_cmd python3
require_cmd pip
require_cmd make

# Main 
git clone --depth 1 https://github.com/Parmeggiani-Lab/elfin.git

cd elfin
./fetch_resources

# Python
virtualenv -p python3 .venv
. ./activate
pip install -r requirements.txt
