#!/bin/bash

# Main 
git clone --depth 1 git@github.com:joy13975/elfin.git
cd elfin
./fetch_resources

# Python
virtualenv -p python3 .venv
. ./activate
pip install -r requirements.txt

# Solver (v1)
git clone --single-branch -b v1 --depth 1 git@github.com:joy13975/elfin-solver.git
cd elfin-solver
make -j4
cd ..

