trap "exit" INT
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14-D14_j1_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14-D14_j1_D18.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14-D14_j1_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14-D14_j1_D76.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14-D14_j1_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14-D14_j1_D81.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14-D14_j2_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14-D14_j2_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14-D14_j2_D71.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14-D14_j2_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14-D14_j3_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14-D14_j4_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14-D14_j5_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14-D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D14-D14_j1_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D14-D14_j1_D18.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D14-D14_j1_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D14-D14_j1_D76.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D14-D14_j1_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D14-D14_j1_D81.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D14-D14_j2_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D14-D14_j2_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D14-D14_j2_D71.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D14-D14_j2_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D14-D14_j3_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D14-D14_j4_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D14-D14_j5_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D14-D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D18-D18_j1_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D18-D18.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D54-D54_j1_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D54-D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D76-D76.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D79-D79_j1_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D79-D79_j2_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D79-D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j1_D81-D81.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j2_D14-D14_j1_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j2_D14-D14_j1_D18.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j2_D14-D14_j1_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j2_D14-D14_j1_D76.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j2_D14-D14_j1_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j2_D14-D14_j1_D81.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j2_D14-D14_j2_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j2_D14-D14_j2_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j2_D14-D14_j2_D71.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j2_D14-D14_j2_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j2_D14-D14_j3_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j2_D14-D14_j4_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j2_D14-D14_j5_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j2_D14-D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j2_D54-D54_j1_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j2_D54-D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j2_D71-D71.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j2_D79-D79_j1_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j2_D79-D79_j2_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j2_D79-D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j3_D54-D54_j1_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j3_D54-D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j4_D79-D79_j1_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j4_D79-D79_j2_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j4_D79-D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j5_D79-D79_j1_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j5_D79-D79_j2_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D14_j5_D79-D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D18-D18_j1_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D18-D18.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D18_j1_D14-D14_j1_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D18_j1_D14-D14_j1_D18.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D18_j1_D14-D14_j1_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D18_j1_D14-D14_j1_D76.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D18_j1_D14-D14_j1_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D18_j1_D14-D14_j1_D81.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D18_j1_D14-D14_j2_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D18_j1_D14-D14_j2_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D18_j1_D14-D14_j2_D71.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D18_j1_D14-D14_j2_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D18_j1_D14-D14_j3_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D18_j1_D14-D14_j4_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D18_j1_D14-D14_j5_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D18_j1_D14-D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49-D49_j1_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49-D49_j1_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49-D49_j1_D81.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49-D49.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49_j1_D14-D14_j1_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49_j1_D14-D14_j1_D18.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49_j1_D14-D14_j1_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49_j1_D14-D14_j1_D76.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49_j1_D14-D14_j1_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49_j1_D14-D14_j1_D81.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49_j1_D14-D14_j2_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49_j1_D14-D14_j2_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49_j1_D14-D14_j2_D71.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49_j1_D14-D14_j2_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49_j1_D14-D14_j3_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49_j1_D14-D14_j4_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49_j1_D14-D14_j5_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49_j1_D14-D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49_j1_D79-D79_j1_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49_j1_D79-D79_j2_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49_j1_D79-D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D49_j1_D81-D81.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D4-D4_j1_D64.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D4-D4.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D4_j1_D64-D64.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D53-D53_j1_D4.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D53-D53_j1_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D53-D53.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D53_j1_D4-D4_j1_D64.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D53_j1_D4-D4.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D53_j1_D79-D79_j1_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D53_j1_D79-D79_j2_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D53_j1_D79-D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D54-D54_j1_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D54-D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D54_j1_D79-D79_j1_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D54_j1_D79-D79_j2_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D54_j1_D79-D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D64-D64.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D71-D71.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D76-D76.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D79-D79_j1_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D79-D79_j2_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D79-D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D79_j1_D54-D54_j1_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D79_j1_D54-D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D79_j2_D14-D14_j1_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D79_j2_D14-D14_j1_D18.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D79_j2_D14-D14_j1_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D79_j2_D14-D14_j1_D76.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D79_j2_D14-D14_j1_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D79_j2_D14-D14_j1_D81.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D79_j2_D14-D14_j2_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D79_j2_D14-D14_j2_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D79_j2_D14-D14_j2_D71.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D79_j2_D14-D14_j2_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D79_j2_D14-D14_j3_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D79_j2_D14-D14_j4_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D79_j2_D14-D14_j5_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D79_j2_D14-D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D81-D81.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/pair/D8-D8.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D14_j1_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D14_j1_D18.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D14_j1_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D14_j1_D76.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D14_j1_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D14_j1_D81.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D14_j2_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D14_j2_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D14_j2_D71.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D14_j2_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D14_j3_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D14_j4_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D14_j5_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D18_j1_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D18.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D49_j1_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D49_j1_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D49_j1_D81.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D49.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D4_j1_D64.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D4.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D53_j1_D4.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D53_j1_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D53.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D54_j1_D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D64.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D71.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D76.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D79_j1_D54.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D79_j2_D14.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D79.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D81.pdb
 ./scripts/Shell/relax.sh ./res/preprocessed_modules/single/D8.pdb
