trap "exit" INT
 ./scripts/Shell/relax.sh ./res/raw_cappings/D14_IC.pdb
 ./scripts/Shell/relax.sh ./res/raw_cappings/D14_NI.pdb
 ./scripts/Shell/relax.sh ./res/raw_cappings/D18_IC.pdb
 ./scripts/Shell/relax.sh ./res/raw_cappings/D18_NI.pdb
 ./scripts/Shell/relax.sh ./res/raw_cappings/D49_IC.pdb
 ./scripts/Shell/relax.sh ./res/raw_cappings/D49_NI.pdb
 ./scripts/Shell/relax.sh ./res/raw_cappings/D4_IC.pdb
 ./scripts/Shell/relax.sh ./res/raw_cappings/D4_NI.pdb
 ./scripts/Shell/relax.sh ./res/raw_cappings/D53_IC.pdb
 ./scripts/Shell/relax.sh ./res/raw_cappings/D53_NI.pdb
 ./scripts/Shell/relax.sh ./res/raw_cappings/D54_IC.pdb
 ./scripts/Shell/relax.sh ./res/raw_cappings/D54_NI.pdb
 ./scripts/Shell/relax.sh ./res/raw_cappings/D64_IC.pdb
 ./scripts/Shell/relax.sh ./res/raw_cappings/D64_NI.pdb
 ./scripts/Shell/relax.sh ./res/raw_cappings/D71_IC.pdb
 ./scripts/Shell/relax.sh ./res/raw_cappings/D71_NI.pdb
 ./scripts/Shell/relax.sh ./res/raw_cappings/D76_IC.pdb
 ./scripts/Shell/relax.sh ./res/raw_cappings/D76_NI.pdb
 ./scripts/Shell/relax.sh ./res/raw_cappings/D79_IC.pdb
 ./scripts/Shell/relax.sh ./res/raw_cappings/D79_NI.pdb
 ./scripts/Shell/relax.sh ./res/raw_cappings/D81_IC.pdb
 ./scripts/Shell/relax.sh ./res/raw_cappings/D81_NI.pdb
